language: go

sudo: false

go:
  - 1.8.1

before_install:
  - go get -u -d -v github.com/Masterminds/glide
  - cd $GOPATH/src/github.com/Masterminds/glide && go install
  - cd $HOME/gopath/src/github.com/lukasmalkmus/tankerkoenig_exporter

install:
  - glide install

script:
  - make test