language: go

go:
  - 1.9
  - tip

before_install:
  - go get github.com/golang/dep/...
  - go get github.com/mattn/goveralls

install:
  - dep ensure --vendor-only

script:
  - $GOPATH/bin/goveralls -service=travis-ci